A01:
  dirout: "/home/datawork-cersat-public/cache/project/sarwave/data/products/experiments/grd"
  res: "100m"
  tile_size:  17000
  periodo_width: {'sample': 2000., 'line': 2000.}
  periodo_overlap: {'sample': 1000., 'line': 1000.}
  lowpass_width: {'line': 4750., 'sample': 4750.}
  scatt_mode: "wst"
  norient: 8
  auxilliary_dataset:
    ecmwf_0100_1h:
      step: 1
      pattern: "/home/datawork-cersat-public/provider/ecmwf/forecast/hourly/0100deg/netcdf_light/%Y/%j/ECMWF_FORECAST_0100_%Y%m%d%H%M_10U_10V.nc"
      name: "ecmwf_0100_1h"
    ww3_global_yearly_3h:
      step: 3
      pattern: "/home/datawork-WW3/PROJECT/SARWAVE/HINDCAST/GLOBAL_NOGQM*/3*/GLOB-30M/*/FIELD_NC/LOPS_WW3-GLOB-30M_%Y%m.nc"
      name: "ww3_global_yearly_3h"
